version: '2.1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # to mount custom nginx.conf
    ports:
      - "80:80"